-- Drop the previously created log table
drop table logs cascade constraint purge;
-- Create a log table
create table logs (
   logId 	number generated by default as identity primary key,
   tableName 	varchar2(50),
   transName 	varchar2(20),
   transDate	date,
   userName 	varchar2(30)
);
